"""Add phone column to Teacher

Revision ID: ad8239762d29
Revises: f284c91e766c
Create Date: 2025-07-30 18:31:39.506639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad8239762d29'
down_revision: Union[str, Sequence[str], None] = 'f284c91e766c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Courses', sa.Column('department', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Courses', 'department')
    # ### end Alembic commands ###
